trigger:
- main

pool:
  name: 'vishal agent pool'

jobs:
- deployment: DeployToMac
  displayName: "Deploy Job to Mac"
  environment: "Dev"  # must match the name of your environment
  strategy:
    runOnce:
      deploy:
        steps:
        - script: |
            echo "Message: $(myMessage)"
            mkdir -p "$HOME/Documents/$(myFolder)"
            echo "Created folder: $(myFolder)"
          displayName: "Create folder in environment"
